name: Build portfolio website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20.10.0-alpine

    env:
      GHA_PAT: ${{ secrets.GHA_PAT }}

    steps:
      - uses: actions/checkout@v2

      - name: Add Git
        run: |
          apk update
          apk add git rsync
          apk add git
          git --version
          rsync --version

      - name: Install Next.js CLI
        run: npm install next react react-dom

      - name: Install NPM packages
        run: npm install

      - name: Build webpage
        run: |
          echo "mfennelly.dev" > public/CNAME
          npx next build

      - name: Clone github-pages branch
        run: git clone -b github-pages https://$GHA_PAT@github.com/mikeyfennelly1/mfennelly.dev/ github-pages

      - name: Copy website to github-pages branch
        run: |
          rsync -av --progress ./out/ github-pages --delete

      - name: Add .nojekyll file
        run: touch github-pages/.nojekyll

      - name: Push github-pages branch changes
        run: |
          tree
          cd github-pages
          git config --global user.email "mikeyp.fennelly@gmail.com"
          git config --global user.name "Mikey Fennelly"
          pwd
          git add --all
          git commit -m "committing all" || echo "No changes to commit"
          git push https://$GHA_PAT@github.com/mikeyfennelly1/mfennelly.dev/ github-pages
